# Generated by Django 5.1.5 on 2025-02-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moughataa',
            name='polygon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='polygon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
