# Generated by Django 5.1.4 on 2025-01-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproducts',
            old_name='cart_product',
            new_name='cart',
        ),
    ]
