# Generated by Django 5.1.5 on 2025-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_moughataa_polygon_wilaya_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='polygon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
