# Generated by Django 5.1.5 on 2025-02-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_commune_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productprice'),
        ),
    ]
