# Generated by Django 5.1.5 on 2025-01-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_moughataa_label_moughataa_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofsale',
            options={'ordering': ['code']},
        ),
    ]
