# Generated by Django 5.1.5 on 2025-01-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pointofsale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofsale',
            options={},
        ),
    ]
