# Generated by Django 5.1.5 on 2025-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartproducts_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='moughataa',
            name='inpc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
