# Generated by Django 5.1.5 on 2025-01-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pointofsale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
