# Generated by Django 5.1.5 on 2025-01-24 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_productprice_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartproducts', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
